### ISSUE TITLE
我安装的插件没有问题，图鉴也更新了，为什么向机器人发请求却没有响应

### ISSUE THREAD

**Issue by zxhsand** [Nwflower/Atlas#10]
![WGF4D3P71R2HWZ`KJ8ZB)87](https://user-images.githubusercontent.com/129765291/229535191-7b4aac99-86d2-43cc-86cd-c51d76a234c7.png)
![X)H@F8`02AZ)ISYZF$D(~ P](https://user-images.githubusercontent.com/129765291/229535353-3626dcb3-d661-4c27-bbc2-7339d730e685.png)

**Comment by zxhsand** [comment]
![$ (HJ%HI0HAA1 TZ5KI)3IC](https://user-images.githubusercontent.com/129765291/229536203-87e2191d-65a6-450e-b1b3-395e9bc7bdd9.png)

**Comment by zxhsand** [comment]
这个是云崽根目录下的genshin-atlas
![PC3 9}P B~4$UAIG0@0``~P](https://user-images.githubusercontent.com/129765291/229538088-ce736c5e-5615-4310-868e-f17fd887eb60.png)
这个是atlas
![$6P(P4H995F(E9$95O ZF 3](https://user-images.githubusercontent.com/129765291/229538172-53f50fa9-9057-478c-bf10-9a1d2cc1298d.png)
这个是atlas目录里面genshin-atlas的目录
![6UWE{L88`07E2VX$OVJ_}(A](https://user-images.githubusercontent.com/129765291/229538396-593ec9c4-5132-446f-96c1-f9539716acc0.png)

**Comment by Nwflower** [comment]
注意，Atlas下的genshin-atlas文件夹不应为空，你也可以把云崽根目录下的genshin-atlas文件夹移动到Atlas下
