### ISSUE TITLE
#xxx在哪里    指令回复异常

### ISSUE THREAD

**Issue by 87174704** [Nwflower/Atlas#12]
之前应该是下载失败过一两张图，然后在这之后发送对应指令的图就都裂了。

求问对应的图和关联都存在哪里了？

**Comment by Nwflower** [comment]
可以手动pull：https://gitee.com/Nwflower/genshin-atlas

**Comment by 87174704** [comment]
这个软件从minigg下载的图片是存储在那个路径的？

**Comment by Nwflower** [comment]
很抱歉，本插件不会从任何第三方地址下载图片。您可能问的是其他插件的问题。
