### ISSUE TITLE
崩铁索引问题

### ISSUE THREAD

**Issue by lish2018** [Nwflower/Atlas#16]
![image](https://user-images.githubusercontent.com/47213596/235506379-c2c7a810-899f-462c-8400-26ca8d162ee3.png)
![image](https://user-images.githubusercontent.com/47213596/235506394-81e3f105-1ed9-46c6-9f17-4a6377160c5f.png)
在Atlas/resource/Forlibrary/star-rail-atlas/othername下的role.yaml文件中重复的黑塔导致yaml解析错误，整合成一个之后解决

**Comment by Nwflower** [comment]
已经修复
