### ISSUE TITLE
本体使用Github源时使用指令更新的图库能否也从github拉取

### ISSUE THREAD

**Issue by TheTychoStar** [Nwflower/Atlas#20]
因为服务器在海外所以用的github源，通过机器人#图鉴升级时，发现还是从gitee的仓库下载，速度很慢经常失去响应。
于是手动git clone了github上的图库，但是发现再次使用#图鉴升级时，又被替换回gitee的图库了。
有点头疼，能否把自动升级图库时的来源设置成和Atlas本体一样的源？或者在升级命令时可以选择使用github还是gitee。

另外手动clone github上的图库之后，每次登陆还会报错“Atlas图鉴拓展包没有正确安装或者不是最新版本。请发送指令 #图鉴升级 以获取或升级Atlas图鉴拓展包”。

**Comment by Nwflower** [comment]
已经了解 下一次会考虑这个需求

**Comment by Nwflower** [comment]
已经更新该功能，删除现在的图鉴库后，使用命令 #github原神图鉴升级 以及 #github星铁图鉴升级即可

**Comment by TheTychoStar** [comment]
> 已经更新该功能，删除现在的图鉴库后，使用命令 #github原神图鉴升级 以及 #github星铁图鉴升级即可

感谢大大，这样就方便了！

**Comment by TheTychoStar** [comment]
不好意思大大我要reopen一下这个issue。刚刚晚上回来测试了一下，github的升级命令没有效果，但原来gitee的图鉴升级命令都表现正常。
看了日志，好像机器人没有识别#github开头的升级命令，发送以后完全没有响应。感觉可能是命令的判断部分出了问题？
![image](https://github.com/Nwflower/Atlas/assets/75252778/45cc8b98-47ba-4601-8bcb-3d054016d5db)

**Comment by Nwflower** [comment]
刚刚看了一下，是因为没有做指令匹配，现在测试没有问题了

**Comment by TheTychoStar** [comment]
> 

测试了一下，虽然指令能识别了，但是生成的图库里，remote url还是指向的gitee的仓库。已经先彻底删除了本地图库以后再执行的#github原神/星铁图鉴升级。

**Comment by TheTychoStar** [comment]
> 我尝试修复了，测试也过了，现在应该没问题了

现在一切正常了，谢谢大佬！
