### ISSUE TITLE
与喵喵插件抢指令，请教能否同时执行指令？

### ISSUE THREAD

**Issue by ikashana** [Nwflower/Atlas#21]
很喜欢本插件图鉴的排版，但是部分指令与喵喵插件重复，导致例如#刻晴 等仅能展示喵喵插件的角色卡片和wiki，不能展示Atlas的图鉴，不知道能不能实现同时发送两个插件的结果。还是说只能通过修改Atlas的优先级或者修改匹配规则来展示Atlas图鉴的结果？

**Comment by Nwflower** [comment]
将Atlas/resource/config.yaml中的匹配指令拦截改为false

**Comment by ikashana** [comment]
> 将Atlas/resource/config.yaml中的匹配指令删截改为false

修改完后重启，依旧无法同时执行。

![QQ图片20230531102001](https://github.com/Nwflower/Atlas/assets/115872923/54fb5d98-72ad-4789-95d0-5cefd4e14b89)

**Comment by Nwflower** [comment]
Atlas的指令是*姬子

**Comment by ikashana** [comment]
> Atlas的指令是*姬子

之前改过星铁的规则，因为用*的话，chatgpt也会回复，所以直接用#了...之前用#姬子是可以的，29号喵喵插件更新星铁的功能后开始抢Altas的指令就行不行了。用#刻晴 也试了，还是这样。
![QQ图片20230531104145](https://github.com/Nwflower/Atlas/assets/115872923/49a07ec1-87f8-4614-bf38-089dcc67ceeb)

**Comment by Nwflower** [comment]
那这个可能暂时没有解决办法

**Comment by ikashana** [comment]
> 那这个可能暂时没有解决办法

好的。那我换个思路实现指向性使用Altas好了，我把原神的rule里正则加上了#原神，用这个来使用Altas的，用#角色名来用喵喵的。之后可能也有人会有类似问题，当参考了，有更好的办法踹我一脚哈哈哈
