### ISSUE TITLE
执行图鉴升级后bot提示Atlas图鉴图片资源升级完毕，但进行查询后控制台仍ERRO:Atlas图鉴拓展包没有正确安装或者不是最新版本。请发送指令#图鉴升级以获取或升级Atlas图鉴拓展包。

### ISSUE THREAD

**Issue by bljszxy** [Nwflower/Atlas#3]

**Comment by Nwflower** [comment]
您好，能否提供一下以下几张图片：
atlas文件夹目录截图
genshin-atlas文件目录截图
以便于我们诊断问题

**Comment by bljszxy** [comment]
![atlas](https://user-images.githubusercontent.com/107937346/217480798-122fca96-9fca-410e-8589-d3471ece692f.jpg)
![genshin-atlas](https://user-images.githubusercontent.com/107937346/217480828-a37e1908-13be-4d90-9dd4-55aa27a7ff79.jpg)
按照您所说的进行查看，发现genshin-atlas文件夹为空。

**Comment by Nwflower** [comment]
可能由于某些原因，genshin-atlas仓库没有正确克隆。按照以下方法解决：
1、删除genshin-atlas空文件夹
2、在Atlas文件夹下手动执行执行命令git clone --depth=1 https://gitee.com/Nwflower/genshin-atlas ./Genshin-atlas
图片资源仓库克隆完毕后即可正常使用。

**Comment by bljszxy** [comment]
按照您的办法成功解决了我遇到的问题，非常感谢您耐心细致的帮助。

**Comment by Tangyc666** [comment]
同d但我带有文件仍然报错：“Atlas图鉴拓展包没有正确安装或者不是最新版本。请发送指令#图鉴升级以获取或升级Atlas图鉴拓展包”
![5XMFBF~HMLY9CEZX0` Z0EO](https://user-images.githubusercontent.com/123861597/218273117-72357aec-669f-4533-b303-39ac410f6e83.png)

**Comment by Tangyc666** [comment]
![JMUB9I4X`F}4LDHZ)`7EZ)U](https://user-images.githubusercontent.com/123861597/218273211-b1af5d92-39d8-43fc-8284-f6314b19faff.png)
![5_BCDWSW~QJT`_MUGTVACDP](https://user-images.githubusercontent.com/123861597/218273227-d38fa5bd-571b-4263-8019-90ade13e61b9.png)
<<==文件夹情况

**Comment by Tangyc666** [comment]
> 
更新报错
![W8~KG7R1ZK1%_KPT)J6FT`U](https://user-images.githubusercontent.com/123861597/218274362-5e1eb389-e16f-467a-93af-5db6ac31ad63.png)

**Comment by Nwflower** [comment]
> ![JMUB9I4XF}4LDHZ)7EZ)U](https://user-images.githubusercontent.com/123861597/218273211-b1af5d92-39d8-43fc-8284-f6314b19faff.png) ![5_BCDWSW~QJT`_MUGTVACDP](https://user-images.githubusercontent.com/123861597/218273227-d38fa5bd-571b-4263-8019-90ade13e61b9.png) <<==文件夹情况

目录不正确。genshin-atlas应该在atlas文件夹内，自行移动文件夹后重试。

**Comment by Tangyc666** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nwflower/Atlas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nwflower/Atlas] 执行图鉴升级后bot提示Atlas图鉴图片资源升级完毕，但进行查询后控制台仍ERRO:Atlas图鉴拓展包没有正确安装或者不是最新版本。请发送指令#图鉴升级以获取或升级Atlas图鉴拓展包。 (Issue #3)





  
  <<==文件夹情况
  
目录不正确。genshin-atlas应该在atlas文件夹内，自行移动文件夹后重试。
