### ISSUE TITLE
指令重复

### ISSUE THREAD

**Issue by ReFenter** [Nwflower/Atlas#4]
![52)QYETU$0URCCC_{NQU@FW](https://user-images.githubusercontent.com/116624612/219014745-1c87d3d2-a450-47b6-b830-0c4e7b077657.png)
![KBMVT82{ 2V(C`}G2F14N0W](https://user-images.githubusercontent.com/116624612/219014754-18d02252-463d-40eb-9c86-0d9e2b164956.png)
![~XQLXKDK3)JUZ~N7NB{8AJN](https://user-images.githubusercontent.com/116624612/219014761-ae149003-216f-46e5-bb85-93bef97e0b19.png)
![2@UJ53BI`2B1{R@3Y_{WNEJ](https://user-images.githubusercontent.com/116624612/219014765-4a62c196-e403-4feb-8520-8d8d2674306c.png)

这个#角色和#天赋触发七圣召唤的聊天记录的指令在哪里修改

**Comment by Nwflower** [comment]
已确认未经任何修改的插件无此问题
自行查看readme第五点进行修改或者重装
