### ISSUE TITLE
似乎昨晚的更新有点问题?

### ISSUE THREAD

**Issue by 8852690** [Nwflower/Atlas#45]
![@J_D@4B%GC%WEJB(~D2LF~9](https://github.com/Nwflower/Atlas/assets/59615518/d5c1bdfd-080a-4d8b-9f0d-747d889b4f93)

**Comment by Nwflower** [comment]
你没更新完全，再手动更新一下

**Comment by 8852690** [comment]
> 你没更新完全，再手动更新一下

Emmm...我早上彻底重拉了一遍的，看起来似乎是这一段有问题。
![image](https://github.com/Nwflower/Atlas/assets/59615518/2687e7af-528e-4945-9918-452b98e26411)

**Comment by Nwflower** [comment]
更新一下插件本体，不要去更新图片库

**Comment by 8852690** [comment]
好吧，估计是之前github没同步到
