### ISSUE TITLE
关于一些原魔不知道怎么触发指令的问题，希望写个列表

### ISSUE THREAD

**Issue by afeathered-sheep** [Nwflower/Atlas#5]
例如一些周本boss，（比如公子）希望能像逍遥图鉴一样写一个索引（），然后希望能写一个元素共鸣效果（因为感觉这个有一点需要（偶尔记不起来），虽然不难，但是没人写）
例如发送：双水/愈疗之水
返回图片，图片有如下字样：火元素附着的持续时间下降40%。生命值上限提升25%
这样子

**Comment by Nwflower** [comment]
你提出/发现的意见/建议/BUG/功能性调整已被采纳/调整/修复，并已在当前的版本推送上线，请在更新至项目最新版/内测版/开发版后查看或阅览，真诚地感谢你对FLOWER/ATLAS/AUTO项目做出的卓越贡献
