### ISSUE TITLE
圣显之钥的图鉴似乎数据有问题

### ISSUE THREAD

**Issue by AshenAshes** [Nwflower/Atlas#6]
特效里的20%生命，应该是生命值提升(20%/25%/30%/35%/40%)。

**Comment by Nwflower** [comment]
你提出/发现的意见/建议/BUG/功能性调整已被采纳/调整/修复，并已在当前的版本推送上线，请在更新至项目最新版/内测版/开发版后查看或阅览，真诚地感谢你对FLOWER/ATLAS/AUTO项目做出的卓越贡献
