### ISSUE TITLE
原魔索引中 boss阶段带括号的选项全部无法响应

### ISSUE THREAD

**Issue by Lopez546** [Nwflower/Atlas#7]
例：#原魔 
4
24（正常触发）
25-37（失效）
#原魔名 （正常触发）
#原魔名（第X阶段）（失效，已尝试更改中英文括号均无效）

**Comment by Lopez546** [comment]
尝试后，公子，女士，正机之神，若陀龙王手动输入原魔名，并去掉括号，不带空格，可以触发。“七叶寂照秘密主”“祸津御建鸣神命”关键词+阶段仍旧无法触发。疑似关键词匹配存在问题。

**Comment by Lopez546** [comment]
Altas版本最新更新日志内容为：[03-01 16:11]删除开发环境提示信息

**Comment by Lopez546** [comment]
更新源为：gitee仓库

**Comment by Nwflower** [comment]
别名文件异常，将随下次更新atlas时一起修复。
在这之前，您可以使用#公子3这样的口令来替代#公子（第三阶段）
