### ISSUE TITLE
#五星武器 触发重复

### ISSUE THREAD

**Issue by howe0116** [Nwflower/Atlas#9]
不设置后缀关键词的话，武器索引中的#五星武器和#四星武器 与Yunzai的指令重复了，如下图
![image](https://user-images.githubusercontent.com/16703666/225308196-7a6e5ed8-534b-4b81-bbeb-115fec986aed.png)

**Comment by Nwflower** [comment]
额，我觉得这个指令可能并非是想触发云崽的这个指令
